Feature/refactor express
ProgramadorRanzinza/ITeacher pull request #12
Opened 2020-08-04 06:59 UTC by LuizPiresS

Acho que agora ta tudo funcionando, acho que reverti as desgraças que fiz no último pr

2020-08-04 15:17 UTC, is-equal requested changes
Sugestão para cada rota ao invés de chamar o APP fazer o seguinte:


```ts
import { Router } from 'express';

function UserRoute(): Router {

return Router()
    .get('/', <Content>)
    .get('/:id', <Content>)
    .post('/', <Content>)
    .delete('/:id', <Content>);

}
```

Carregando a rota:
```ts
app.use('/user', UserRoute());
```

2020-08-04 15:17 UTC, matheusalbino commented on src/adapters/api/create-user-json.presenter.ts
>  export class CreateUserJSONPresenter implements Presenter<CreateUserResponse> {
Como vai ter só JSON faz sentido ter explicito o JSON?

2020-08-04 15:17 UTC, matheusalbino commented on src/database/data-sources/user.data-source.ts
> +  }
Nesses casos não seria melhor realizar um count ao invés de findOne, e verificar se retornou ZERO e talz ?

2020-08-05 12:42 UTC, LuizPiresS commented on src/adapters/api/create-user-json.presenter.ts
>  export class CreateUserJSONPresenter implements Presenter<CreateUserResponse> {
No próximo pr vou colocar estas modificações

2020-08-05 12:43 UTC, LuizPiresS commented on src/database/data-sources/user.data-source.ts
> +  }
No próximo pr vou colocar estas modificações

2020-08-05 12:57 UTC, closed without merging